### ISSUE TITLE
Never Validates

### ISSUE THREAD

**Issue by Foggalong** [leny/atom-w3c-validation#15]
> W3C Markup Validation Service Report - Validation pending (this can take some time)...

Been waiting over an hour now, still no output :(

**Comment by leny** [comment]
Hi, thanks for the report.
For now, I'm quite busy with some pro work.
I will not be able to review this until january. Feel free to investigate and submit a Pull Request if you find something!

**Comment by Foggalong** [comment]
I'm not a JS/CoffeScript dev but I'll have a look see what I can find :)

**Comment by leny** [comment]
Hi, sorry for the _long_ time on this one, was very busy with my work.

I've just released a new version (`0.3.0`) of the package, using new modules for validation.

Hope it will fix this issue.
