### ISSUE TITLE
Validation pending (this can take some time)... - W3C HTML CSS Validation Service works

### ISSUE THREAD

**Issue by paul-pauliskolan** [leny/atom-w3c-validation#46]
Message: "Validation pending (this can take some time)... " in Atom

- W3C HTML CSS Validation Service web sites works
- https://validator.w3.org/
- https://jigsaw.w3.org/css-validator/

**Comment by kofiopoku** [comment]
Having the same issue

**Comment by SnorflSnort** [comment]
I started getting this issue as well. Even in an empty html document it displays the error message. I have already attempted to  reinstall atom-w3c-validation, Atom and disabling all other packages. Nothing seems to work.

**Comment by courtneyjcunningham** [comment]
Did y'all ever figure out a fix for this? I've installed it on 2 different computers today and both are throwing these codes: 
"Validation pending (this can take some time)..."
 "Validation fails without error."

**Comment by QueenGene** [comment]
Having the same issue (with over 15 different users in my class...)

**Comment by SnorflSnort** [comment]
Unfortunately I couldn't figure out a fix for the issue. Instead I started using [htmlhint](https://atom.io/packages/htmlhint) to validate html (not css). You must install these packages as well; [linter-htmlhint](https://atom.io/packages/linter-htmlhint) and [linter](https://atom.io/packages/linter).

Hopefully atom-w3c-validation gets fixed soon.

**Comment by jrene3** [comment]
I've been having the same issue as everyone above. Hopefully this can get resolved soon.

**Comment by paul-pauliskolan** [comment]
I decided to change editor to VS Code and use https://marketplace.visualstudio.com/items?itemName=Umoxfo.vscode-w3cvalidation that works like atom-w3c-validation

**Comment by charmarkk** [comment]
Has there been any work or interest in this still, @leny? This plugin is a great help to myself and the students I teach web accessibility to, and the plugin seems to have broken.

**Comment by paul-pauliskolan** [comment]
Since Atom been archived I figure it's a slime chance anybody want to fix add ons. As i wrote July 2022 "I _decided to change editor to VS Code and use https://marketplace.visualstudio.com/items?itemName=Umoxfo.vscode-w3cvalidation that works like atom-w3c-validation"

**Comment by charmarkk** [comment]
That's unfortunate - Atom got resurrected as Pulsar and is still able to use all the same plugins etc. and Atom/Pulsar works best for my needs. Thanks.
